version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aiyzajunaid/frontend-app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aiyzajunaid/backend-api
    ports:
      - "5000:5000"
    env_file:
      - .env

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: aiyzajunaid/auth-service
    ports:
      - "5001:5001"
    env_file:
      - .env
